
PLAYER_WINDOW_TITLE = "Hunter"
PLAYER_WINDOW_SIZE = (100, 100)
PLAYER_WINDOW_COLOR = "black"
PLAYER_WINDOW_SPEED = 5


TARGET_WINDOW_COUNT = 5
TARGET_WINDOW_TITLE = "Target"
TARGET_WINDOW_SIZE = (200, 150)
TARGET_WINDOW_COLORS = ["red", "blue", "green", "yellow", "purple"]


SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
GAME_TITLE = "Window Hunter"
SCORE_INCREMENT = 10


TARGET_FPS = 60
UPDATE_INTERVAL = 1000 // TARGET_FPS  


SHAPE_TYPES = ["rectangle", "triangle"] 
WINDOW_ALPHA = 0.8  
