WIDTH = 1024
HEIGHT = 768
FPS = 60
TITLE = "Advanced Water Simulation"

BG_COLOR = (0, 10, 20)
UI_COLOR = (220, 220, 220)
UI_BG_COLOR = (40, 40, 45, 180)
BUTTON_COLOR = (60, 60, 80)
BUTTON_HOVER_COLOR = (80, 80, 100)
BUTTON_TEXT_COLOR = (240, 240, 240)
WATER_COLOR = (10, 150, 255)
WATER_COLOR_VARIATION = 30
OBJECT_COLOR = (155, 85, 25)
GLASS_COLOR = (200, 230, 255, 100)

SIM_PARTICLE = "particle"
SIM_SPH = "sph"
SIM_GRID = "grid"
SIM_TYPES = [SIM_PARTICLE, SIM_SPH, SIM_GRID]

GRAVITY = 9.81 * 0.25
WATER_DENSITY = 0.5
VISCOSITY = 0.1
PARTICLE_RADIUS = 4.0
PARTICLE_MASS = 1.0

SMOOTHING_LENGTH = PARTICLE_RADIUS * 4.0
SMOOTHING_LENGTH_SQ = SMOOTHING_LENGTH * SMOOTHING_LENGTH
GAS_CONSTANT = 2000.0
REST_DENSITY = 1000.0
MASS = 65.0
VISCOSITY_STRENGTH = 0.08
SURFACE_TENSION = 0.0728

MAX_PARTICLES_PER_CLICK = 10

CELL_SIZE = 4
GRID_WIDTH = WIDTH // CELL_SIZE
GRID_HEIGHT = HEIGHT // CELL_SIZE
EMPTY = 0
WATER = 1
SOLID = 2
AIR_PRESSURE = 0.1
FLOW_SPEED = 4

FONT_SIZE_LARGE = 36
FONT_SIZE_MEDIUM = 24
FONT_SIZE_SMALL = 18

STATE_MENU = "menu"
STATE_SIMULATION = "simulation"
STATE_PAUSED = "paused"
STATE_SETTINGS = "settings"

OBJ_RECT = "rectangle"
OBJ_CIRCLE = "circle"
OBJ_POLYGON = "polygon"
OBJ_GLASS = "glass"

RESTITUTION = 0.4
FRICTION = 0.9

SCENE_EMPTY = "empty"
SCENE_BUCKET = "bucket"
SCENE_POOL = "pool"
SCENE_WATERFALL = "waterfall"
SCENE_MAZE = "maze"
SCENE_FOUNTAIN = "fountain"
SCENES = [SCENE_EMPTY, SCENE_BUCKET, SCENE_POOL, SCENE_WATERFALL, SCENE_MAZE, SCENE_FOUNTAIN]